### ISSUE TITLE
Update website in cabal file

### ISSUE THREAD

**Issue by jstolarek** [haskell/hoopl#27]
Cabal file currently points to http://ghc.cs.tufts.edu/hoopl/ as the website of the library. But there is nothing really useful there - just a bunch of redirections. Can we offer a better link?

**Comment by michalt** [comment]
Maybe we can just point it to github and have the README point to the paper as well as some of the relevant pages (tickets?) on GHC's trac?

**Comment by jstolarek** [comment]
I would point to github. Readme already points to the paper. I would refrain from point to Trac.

**Comment by michalt** [comment]
Sounds good to me.
