### ISSUE TITLE
Conditional jumps with fall-through not always ordered properly by postorder_dfs

### ISSUE THREAD

**Issue by hth313** [haskell/hoopl#44]
When flattening the blocks to a final linear output order, `postorder_dfs` seems useful. One of my exit nodes is a `CondJump`, which has a destination and a fall-through label that is expected to be the next block in the flattened CFG.

This works most of the time, but there are cases where it fails. Consider the following sequence (an if-then-else) dispatching with a `CondJump`:

```
     CondJump L4 L6 conditional
L6:  ..
     Jump L3
L4:  ..
     Jump L3
L3:
```

There are two blocks `L4` and `L6` (the fall-through) which handles the true and false case of the if. This comes out as expected from `postorder_dfs`.

However, when the conditional expressions contains `&&` and `||`, I need to create a dispatch sequence, and it may be rewritten as:

```
     CondJump L6 L9 conditional'
L9:  CondJump L4 L6 conditional''
L6:  ..
     Jump L3
L4:  ..
     Jump L3
L3:
```

However, `postorder_dfs` comes up with the following:

```
     CondJump L6 L9 conditional'
L9:  CondJump L4 L6 conditional''
L4:  ..
     Jump L3
L6:  ..
     Jump L3
L3:
```

The fall-through label from the second `CondJump` does not follow immediately after!

The reason is that Hoopl has no idea about the concept of conditional jumps, `postorder_dfs` sees the first `CondJump` with `[L6,L9]` and start to process `L6`. This results in that the block acc gets `L6` followed by blocks that comes after it, in this case `L3` and whatever comes after that.

Now acc is `[L6,L3,..]`, and then it looks at `L9` with `[L4,L6]` as children. It starts with `L4` and add whatever comes after (nothing new in this case), so we end up with `[L4,L6,L3,..]`, then it gets to `L6`, but as it is already visited, so it is skipped.

Questions:

1. Should `postorder_dfs` be able to handle this?
2. Should Hoopl know about conditional jumps with fall-through? It does not seem to have such concept now.
3. What is the correct way to flatten the CFG for final output?

**Comment by simonpj** [comment]
I don't understand the problem you are trying to solve. What's wrong with the order that `postorder_dfs` comes up with?

Perhaps you have in mind that after `postorder_dfs` then you can pretty-print as a sequence of machine instructions with a fall-through for the conditional jump?  But you can still get a fall-through by negating the condition can't you?   And none of this matters if generating LLVM.

**Comment by hth313** [comment]
I want a sequence of instructions that have the order as they should appear in the final output. Conditional branches need to be able to fall-through to the next block.

However, it turns out that it is easy to rectify this issue in my case as I need a branch optimizer that works on the flattened output anyway and correcting the potential out of order sequence there is trivial.

So any post processing, be it the way I do it or (apparently) LLVM can easily correct the issue.

I will close this.

**Comment by simonmar** [comment]
In GHC we don't use postorder_dfs to sequence the blocks for fallthroughs,
instead we do what I think amounts to a pre-order traversal (actually it's
an SCC analysis to account for loops):

https://phabricator.haskell.org/diffusion/GHC/browse/master/compiler/nativeGen/AsmCodeGen.hs;14d885e843f6907dbc5048ae66aca25d738e99f7$841-849

Cheers
Simon

**Comment by hth313** [comment]
Thank you! That is very useful information to me, I will keep it in mind for the future as I expect to get back and do more elaborate branch optimizations.
