### ISSUE TITLE
Hoopl not mentioned on "Library submission" page

### ISSUE THREAD

**Issue by jstolarek** [haskell/hoopl#5]
Per [recent discussion](https://mail.haskell.org/pipermail/ghc-devs/2015-May/008919.html) Hoopl should be listed on [Library submission](https://wiki.haskell.org/Library_submissions) Haskell Wiki page in category (3).

**Comment by mlite** [comment]
Agreed. Who can update this page? Should we file a ticket?

**Comment by jstolarek** [comment]
It's a wiki - anyone can do that. At first I wanted to do this myself but I thought that you and Andreas, as maintainers, might have more meaningful information to add to that page. But perhaps I'm wrong and this is just a single entry in the table. In that case I could do that.

**Comment by jstolarek** [comment]
I updated the wiki by adding Hoopl as a core library and listing Ning as the maintainer.
